{"name": "test_newly", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../data_test/send.yaml'", "trace": "self = <test_24.TestProcurementType object at 0x046E7F90>\n\n    def test_newly(self):\n        self.lab = gl.get_value('lab')\n        self.caseid = '%s-24' % (self.lab)\n        self.ip = gl.get_value('apiip')\n        self.testplanid = gl.get_value('test_plan_id')\n        self.token = gl.get_value('Cookie')\n>       self.formIdList = Con().con_read()['formId']\n\ntestcase\\test_24.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <testcase.axtr.Con object at 0x046E7AD0>\n\n    def con_read(self):\n        #打开文件\n>       with open('../data_test/send.yaml', encoding='utf-8') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../data_test/send.yaml'\n\ntestcase\\axtr.py:37: FileNotFoundError"}, "start": 1616491342081, "stop": 1616491342082, "uuid": "fe2884a4-6a38-4989-83ea-401217c09a43", "historyId": "166565f02303a72be260404830bf8f70", "testCaseId": "7f33782f14f87fcdade5148944c02980", "fullName": "testcase.test_24.TestProcurementType#test_newly", "labels": [{"name": "feature", "value": "测试用例24"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_24"}, {"name": "subSuite", "value": "TestProcurementType"}, {"name": "host", "value": "DESKTOP-JR3NDOU"}, {"name": "thread", "value": "194592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_24"}]}