{"name": "test_newly", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'test_dict.yaml'", "trace": "self = <test_10.TestProcurementType object at 0x04EAB630>\n\n    def test_newly(self):\n        self.lab = gl.get_value('lab')\n        self.caseid = '%s-10' % (self.lab)\n        self.ip = gl.get_value('apiip')\n        self.testplanid = gl.get_value('test_plan_id')\n        self.token = gl.get_value('Cookie')\n>       self.formIdList = ReadExtract().read_extract()['formNum']\n\ntestcase\\test_10.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <testcase.axtr.ReadExtract object at 0x04EAB510>\n\n    def read_extract(self):\n        #打开文件\n>       with open('test_dict.yaml', encoding='utf-8') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'test_dict.yaml'\n\ntestcase\\axtr.py:6: FileNotFoundError"}, "start": 1615860544355, "stop": 1615860544355, "uuid": "8642b6be-687e-445b-94e5-cf3175e33b94", "historyId": "dcfbf4dc1704b69fbf645aa7b1fac875", "testCaseId": "94e89502805ebdc9d47528707cc3e0a6", "fullName": "testcase.test_10.TestProcurementType#test_newly", "labels": [{"name": "feature", "value": "测试用例10"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_10"}, {"name": "subSuite", "value": "TestProcurementType"}, {"name": "host", "value": "DESKTOP-JR3NDOU"}, {"name": "thread", "value": "170332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_10"}]}