{"name": "test_newly", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'test_dict.yaml'", "trace": "self = <test_07.TestProcurementType object at 0x051CC330>\n\n    def test_newly(self):\n        self.lab = gl.get_value('lab')\n        self.caseid = '%s-07' % (self.lab)\n        self.ip = gl.get_value('apiip')\n        self.testplanid = gl.get_value('test_plan_id')\n        self.token = gl.get_value('Cookie')\n>       self.id = self.id = ReadExtract().read_extract()['id']\n\ntestcase\\test_07.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <testcase.axtr.ReadExtract object at 0x051CC6F0>\n\n    def read_extract(self):\n        #打开文件\n>       with open('test_dict.yaml', encoding='utf-8') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'test_dict.yaml'\n\ntestcase\\axtr.py:6: FileNotFoundError"}, "start": 1615860543705, "stop": 1615860543705, "uuid": "cf153ddd-2222-4665-8680-c237b92beb38", "historyId": "8b161588a953c64cf26beca11ed8db6b", "testCaseId": "5ae16aab88762868621c31288a32488b", "fullName": "testcase.test_07.TestProcurementType#test_newly", "labels": [{"name": "feature", "value": "测试用例7"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_07"}, {"name": "subSuite", "value": "TestProcurementType"}, {"name": "host", "value": "DESKTOP-JR3NDOU"}, {"name": "thread", "value": "170332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_07"}]}